name: diplom

packages:
  - .
  - packages/*
  - apps/*

command:
  bootstrap:
    environment:
      sdk: '>=3.3.3 <4.0.0'
    dependencies:
      # Here should be listed all common dependencies
      # to update versions in all apps with `melos bootstrap`
      ferry: ^0.16.0+1
      firebase_auth: ^4.19.4
      firebase_core: ^2.30.1
      flutter_bloc: ^8.1.5
      fpdart: ^1.1.0
      gql_http_link: ^1.0.1+1
    dev_dependencies:
      build_runner: ^2.4.9
      ferry_generator: ^0.10.0

scripts:
  analyze:
    run: flutter analyze
    exec:
      concurrency: 1
  
  test:
    exec: flutter test

  install:
    # to install dependency `melos run install <package_name>`
    # to install dev-dependency `melos run install dev:<package_name>`
    exec: dart pub add $1
    packageFilters:
      ignore: diplom

  uninstall:
    exec: dart pub remove $1
    packageFilters:
      ignore: diplom

  schema-generate:
    exec: "dart scripts/schema_generate.dart"
    packageFilters:
      scope: 
        - easy_paint
        - your_meal