name: your_meal
description: "Find the best dish for you!"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  core: 0.1.0+1
  utils: 0.1.0+1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  ferry: ^0.16.0+1
  gql_http_link: ^1.0.1+1
  image_picker: ^1.1.1
  collection: ^1.18.0
  firebase_storage: ^11.7.6
  built_collection: ^5.1.1
  uuid: ^4.4.0
  elastic_client: ^0.3.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ferry_generator: ^0.10.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
