name: core
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  utils: 0.1.0+1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  ferry: ^0.16.0+1
  gql_http_link: ^1.0.1+1
  image_picker: ^1.1.1
  collection: ^1.18.0
  firebase_storage: ^11.7.6

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
